#ifndef DJI_SDK_APP_INFO_H
#define DJI_SDK_APP_INFO_H

#define USER_APP_NAME          "REPLACE_WITH_APP_NAME"
#define USER_APP_ID            "REPLACE_WITH_APP_ID"
#define USER_APP_KEY           "REPLACE_WITH_APP_KEY"
#define USER_APP_LICENSE       "REPLACE_WITH_APP_LICENSE"
#define USER_DEVELOPER_ACCOUNT "REPLACE_WITH_DEVELOPER_ACCOUNT"
#define USER_BAUD_RATE         "921600"

#endif
